blank_issues_enabled: false
contact_links:
  - name: COSCUP 志工系統
    url: https://volunteer.coscup.org
  - name: COSCUP Mattermost
    url: https://chat.coscup.org
    about: COSCUP 使用的溝通平臺
  - name: COSCUP 2025 共筆文件
    url: https://hackmd.io/team/coscup/folders/ZUrsF-lhmjxmb64ZGWt5g
