name: 一般任務
description: 一般任務時，使用的 Template
type: Task
projects:
  - COSCUP/11
body:
  - type: checkboxes
    attributes:
      label: 任務標題請追求言簡意賅
      options:
        - label: "Yes"
  - type: textarea
    attributes:
      label: 任務內容
      description: 描述內容請追求團隊裡有兩個人以上可以完全看懂
